version: '3.3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.6 # Compatible w/ Aurora
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - $HOME/wordgate/logs:/var/log/nginx
      - $HOME/wordgate/nginx:/etc/nginx/conf.d
