version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/logs/nginx:/var/log/nginx
      - ./data/sites:/var/www/html
    links:
      - makerbuildlog
    restart: always

  mysql:
    container_name: mysql
    image: mysql:5.6 # Compatible w/ Aurora
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example

  makerbuildlog:
    container_name: makerbuildlog
    image: inzania/wordgate:latest
    restart: always
    build:
      context: .
    environment:
      WG_S3_BUCKET: inzania
      WG_S3_PATH: sites/makerbuildlog/
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_HOST: mysql
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    volumes:
      - ./data/logs/makerbuildlog:/var/log
      - ./data/sites/makerbuildlog:/var/www/html/makerbuildlog
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "9000:9000"
